/*
 * app_window.c — MainWindow, TextWindow, Sine Wave Animation, Countdown Timer,
 *                Status Bar, TextWindow Screen Boundary Awareness
 *
 * This module implements all GTK3 UI components for the Transcriber application:
 *
 *   1. MainWindow       — Primary application window with microphone icon,
 *                          sine wave animation overlay, and status bar.
 *   2. TextWindow       — Transient utility window for displaying/editing
 *                          transcribed text. Positioned below MainWindow by
 *                          default; if it would extend past the bottom of the
 *                          display monitor, it is positioned above instead.
 *   3. Sine Wave Animation — Cairo-driven animation on GtkDrawingArea during
 *                          STATE_LISTENING only. Rendered in blue (RGB 0,0,1)
 *                          with a line width of 6.0 pixels. Hidden during
 *                          STATE_IDLE and STATE_TRANSCRIBING.
 *   4. Countdown Timer  — GtkLabel in the center of the status bar that counts
 *                          down from max_duration to 0 during STATE_LISTENING.
 *                          Hidden during all other states.
 *   5. Status Bar       — 16-pixel bar with gear button (left), countdown timer
 *                          (center), and connection indicator (right).
 *   6. Config Callback  — Invoked when the Configuration Dialog saves changes,
 *                          allowing the main application to apply runtime config
 *                          updates (e.g., audio device selection).
 *
 * Architecture:
 *   - All GTK widgets are created and managed within this module
 *   - XPM icons loaded from assets/ directory at runtime
 *   - Cairo drawing for sine wave animation and connection indicator
 *   - Timer-driven animation at 30fps (33ms interval)
 *   - Countdown timer updates every 1 second via g_timeout_add_seconds()
 *   - Thread-safe state updates via GTK main context
 */

#define _POSIX_C_SOURCE 200809L

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libgen.h>
#include <limits.h>
#include <unistd.h>

#include "app_window.h"
#include "app_config.h"
#include "app_config_dialog.h"
#include "app_whisper.h"

/* Embedded XPM assets (generated by CMake) */
#ifdef XPM_STATICALLY_EMBEDDED
#include "assets/gear.h"
#include "assets/greenmic.h"
#include "assets/redmic.h"
#endif

/* ------------------------------------------------------------------ */
/* Internal constants                                                  */
/* ------------------------------------------------------------------ */

#define STATUS_BAR_HEIGHT 16
#define INDICATOR_SIZE 8
#define ANIMATION_INTERVAL_MS 33
#define WAVE_PHASE_INCREMENT 0.15
#define WAVE_AMPLITUDE 20.0
#define WAVE_FREQUENCY 0.05
#define WAVE_COLOR_R 0.0
#define WAVE_COLOR_G 0.0
#define WAVE_COLOR_B 1.0
#define WAVE_COLOR_A 0.7
#define WAVE_LINE_WIDTH 6.0

/* Connection indicator colors */
#define COLOR_DISCONNECTED_R 1.0
#define COLOR_DISCONNECTED_G 0.0
#define COLOR_DISCONNECTED_B 0.0
#define COLOR_CONNECTED_R 0.0
#define COLOR_CONNECTED_G 1.0
#define COLOR_CONNECTED_B 0.0
#define COLOR_CHECKING_R 1.0
#define COLOR_CHECKING_G 1.0
#define COLOR_CHECKING_B 0.0
#define COLOR_LOADING_R 1.0
#define COLOR_LOADING_G 0.65
#define COLOR_LOADING_B 0.0

/* Default window position */
#define DEFAULT_WINDOW_X 100
#define DEFAULT_WINDOW_Y 100

/* TextWindow offset below MainWindow */
#define TEXT_WINDOW_OFFSET_Y 10

/* ------------------------------------------------------------------ */
/* Internal structures                                                 */
/* ------------------------------------------------------------------ */

/**
 * Internal MainWindow state.
 *
 * window:           GtkWindow (TOPLEVEL, UTILITY hint)
 * main_box:         Vertical GtkBox containing icon area and status bar
 * icon_area:        GtkDrawingArea where the mic icon is rendered
 * animation_area:   GtkDrawingArea for the sine wave overlay
 * status_bar:       16px GtkBox (gear button left, indicator right)
 * gear_button:      GtkButton with gear.xpm → opens Config Dialog
 * indicator_area:   GtkDrawingArea for the 8x8 connection status circle
 * config:           Pointer to shared AppConfig
 * controller:       Pointer to AppStateController
 * animation_source_id: GLib timeout source ID (0 = not running)
 * wave_phase:       Current phase offset of the sine wave (radians)
 * icon_width:       Width of the microphone icon in pixels
 * icon_height:      Height of the microphone icon in pixels
 * asset_dir:        Path to the assets directory
 * checking_blink:   Blink state for CHECKING connection status
 * checking_source_id: Timer source ID for blink animation
 */
struct _MainWindow {
    GtkWindow *window;
    GtkBox *main_box;
    GtkDrawingArea *icon_area;
    GtkDrawingArea *animation_area;
    GtkBox *status_bar;
    GtkButton *gear_button;
    GtkLabel *countdown_label;
    GtkLevelBar *volume_level_bar;
    GtkDrawingArea *indicator_area;
    AppConfig *config;
    AppStateController *controller;
    WhisperClient *whisper_client;
    guint animation_source_id;
    double wave_phase;
    int icon_width;
    int icon_height;
    char asset_dir[PATH_MAX];
    /* Cached window icons to avoid repeated XPM parsing (M2-002 fix) */
    GdkPixbuf *cached_red_icon;
    GdkPixbuf *cached_green_icon;
    bool checking_blink;
    /* Model loading indicator — true while whisper model is loading at startup.
     * When true, the icon draw callback overlays "WAIT" text on the red mic. */
    bool model_loading;
    guint checking_source_id;
    /* Countdown timer */
    guint countdown_source_id;
    int countdown_seconds;
    /* Toggle callback — invoked when the mic icon is clicked */
    void (*on_toggle)(void *user_data);
    void *toggle_user_data;
    /* Config changed callback — invoked when config dialog saves */
    void (*on_config_changed)(void *user_data);
    void *config_changed_user_data;
};

/**
 * Internal TextWindow state.
 *
 * window:    GtkWindow (TOPLEVEL, UTILITY hint, transient for MainWindow)
 * text_view: GtkTextView providing full editing capabilities
 * buffer:    GtkTextBuffer holding the transcribed text
 */
struct _TextWindow {
    GtkWindow *window;
    GtkTextView *text_view;
    GtkTextBuffer *buffer;
};

/* ------------------------------------------------------------------ */
/* Static helper function declarations                                 */
/* ------------------------------------------------------------------ */

static void get_asset_dir(MainWindow *win);
static GdkPixbuf *load_xpm(MainWindow *win, const char *filename);
static void render_icon(MainWindow *win, const char *icon_name);
static gboolean on_icon_button_press(GtkWidget *widget, GdkEventButton *event, gpointer user_data);
static void on_gear_button_clicked(GtkButton *button, gpointer user_data);
static gboolean on_indicator_button_press(GtkWidget *widget, GdkEventButton *event, gpointer user_data);
static gboolean on_window_delete_event(GtkWidget *widget, GdkEvent *event, gpointer user_data);
static void on_icon_draw(GtkWidget *widget, cairo_t *cr, gpointer user_data);
static void on_animation_draw(GtkWidget *widget, cairo_t *cr, gpointer user_data);
static void on_indicator_draw(GtkWidget *widget, cairo_t *cr, gpointer user_data);
static gboolean animation_tick(gpointer user_data);
static gboolean checking_blink_tick(gpointer user_data);
static void start_checking_blink(MainWindow *win);
static void stop_checking_blink(MainWindow *win);
static gboolean countdown_tick(gpointer user_data);
static GdkPixbuf *get_cached_icon(MainWindow *win, const char *icon_name);

/* TextWindow helpers */
static gboolean on_text_window_delete_event(GtkWidget *widget, GdkEvent *event, gpointer user_data);
static gboolean on_main_window_configure_event(GtkWidget *widget, GdkEventConfigure *event, gpointer user_data);

/* ------------------------------------------------------------------ */
/* Asset management                                                    */
/* ------------------------------------------------------------------ */

/**
 * Determine the path to the assets directory.
 * Looks for assets/ relative to the executable location first,
 * then falls back to the current directory.
 */
static void get_asset_dir(MainWindow *win) {
    /* Try to get the directory of the executable */
    char exe_path[PATH_MAX];
    ssize_t len = readlink("/proc/self/exe", exe_path, sizeof(exe_path) - 1);
    if (len != -1) {
        exe_path[len] = '\0';
        char *dir = dirname(exe_path);
        snprintf(win->asset_dir, sizeof(win->asset_dir), "%s/assets", dir);
    } else {
        /* Fallback: look for assets/ relative to current directory */
        snprintf(win->asset_dir, sizeof(win->asset_dir), "./assets");
    }
}

/**
 * Load an XPM icon into a GdkPixbuf.
 * Prefers embedded XPM arrays (XPM_STATICALLY_EMBEDDED),
 * falls back to loading from disk.
 *
 * Returns a new GdkPixbuf on success, NULL on failure.
 */
static GdkPixbuf *load_xpm(MainWindow *win, const char *filename) {
    (void)win;
#ifdef XPM_STATICALLY_EMBEDDED
    /* Use embedded XPM arrays */
    if (strcmp(filename, "gear.xpm") == 0) {
        return gdk_pixbuf_new_from_xpm_data(GEAR_XPM);
    } else if (strcmp(filename, "greenmic.xpm") == 0) {
        return gdk_pixbuf_new_from_xpm_data(GREENMIC_XPM);
    } else if (strcmp(filename, "redmic.xpm") == 0) {
        return gdk_pixbuf_new_from_xpm_data(REDMIC_XPM);
    }
    return NULL;  /* Unknown XPM filename */
#else
    /* Fallback: load from disk */
    (void)win;
    char path[PATH_MAX];
    g_snprintf(path, sizeof(path), "%s/%s", win->asset_dir, filename);

    GdkPixbuf *pixbuf = gdk_pixbuf_new_from_file(path, NULL);
    if (!pixbuf) {
        /* Fallback: try relative to current directory */
        pixbuf = gdk_pixbuf_new_from_file(filename, NULL);
    }
    return pixbuf;
#endif
}

/**
 * Get a cached GdkPixbuf for the given icon name.
 * Loads and caches the pixbuf on first access, then returns a ref'd copy.
 * (M2-002 fix — avoids repeated XPM parsing on state transitions)
 */
static GdkPixbuf *get_cached_icon(MainWindow *win, const char *icon_name) {
    if (strcmp(icon_name, "redmic.xpm") == 0) {
        if (!win->cached_red_icon) {
            win->cached_red_icon = load_xpm(win, "redmic.xpm");
        }
        if (win->cached_red_icon) {
            g_object_ref(win->cached_red_icon);
            return win->cached_red_icon;
        }
    } else if (strcmp(icon_name, "greenmic.xpm") == 0) {
        if (!win->cached_green_icon) {
            win->cached_green_icon = load_xpm(win, "greenmic.xpm");
        }
        if (win->cached_green_icon) {
            g_object_ref(win->cached_green_icon);
            return win->cached_green_icon;
        }
    }
    return NULL;
}

/* ------------------------------------------------------------------ */
/* Icon rendering                                                      */
/* ------------------------------------------------------------------ */

/**
 * Render the specified icon (redmic.xpm or greenmic.xpm) onto the icon area.
 * Stores the icon dimensions for layout purposes.
 */
static void render_icon(MainWindow *win, const char *icon_name) {
    GdkPixbuf *pixbuf = load_xpm(win, icon_name);
    if (!pixbuf) {
        return;
    }

    win->icon_width = gdk_pixbuf_get_width(pixbuf);
    win->icon_height = gdk_pixbuf_get_height(pixbuf);

    /* Set the drawing area size to match the icon */
    gtk_widget_set_size_request(GTK_WIDGET(win->icon_area),
                                win->icon_width,
                                win->icon_height);
    gtk_widget_set_size_request(GTK_WIDGET(win->animation_area),
                                win->icon_width,
                                win->icon_height);

    /* Set the main window to a square based on the largest icon dimension + status bar */
    int size = (win->icon_width > win->icon_height) ? win->icon_width : win->icon_height;
    size = (size > STATUS_BAR_HEIGHT) ? size : STATUS_BAR_HEIGHT;
    int window_size = size + STATUS_BAR_HEIGHT;
    if (gtk_widget_get_realized(GTK_WIDGET(win->window))) {
        gtk_window_resize(win->window, window_size, window_size);
    } else {
        gtk_window_set_default_size(win->window, window_size, window_size);
    }

    /* Queue a redraw to render the icon */
    /* Use g_object_set_data_full with g_free to prevent leaking the previous strdup */
    g_object_set_data_full(G_OBJECT(win->icon_area), "icon_name", g_strdup(icon_name), g_free);
    gtk_widget_queue_draw(GTK_WIDGET(win->icon_area));

    g_object_unref(pixbuf);
}

/**
 * Draw callback for the icon drawing area.
 * Renders the microphone icon from XPM file.
 * When model_loading is true, overlays "WAIT" text in bold black
 * to inform the user that the system is not yet ready for dictation.
 */
static void on_icon_draw(GtkWidget *widget, cairo_t *cr, gpointer user_data) {
    MainWindow *win = (MainWindow *)user_data;
    const char *icon_name = (const char *)g_object_get_data(G_OBJECT(widget), "icon_name");

    if (!icon_name) {
        return;
    }

    // L-010 fix: Use cached icon instead of loading XPM every draw call
    GdkPixbuf *pixbuf = get_cached_icon(win, icon_name);
    if (!pixbuf) {
        return;
    }

    /* Center the icon in the drawing area */
    int area_width = gtk_widget_get_allocated_width(widget);
    int area_height = gtk_widget_get_allocated_height(widget);
    int icon_w = gdk_pixbuf_get_width(pixbuf);
    int icon_h = gdk_pixbuf_get_height(pixbuf);
    int offset_x = (area_width - icon_w) / 2;
    int offset_y = (area_height - icon_h) / 2;

    gdk_cairo_set_source_pixbuf(cr, pixbuf, offset_x, offset_y);
    cairo_paint(cr);

    g_object_unref(pixbuf);

    /* Overlay "WAIT" text when model is still loading */
    if (win->model_loading) {
        double text_x = area_width / 2.0;
        double text_y = area_height / 2.0;

        /* Use a font size proportional to the icon size */
        int font_size = (area_width < area_height) ? area_width : area_height;
        font_size = font_size / 5;  /* Roughly 20% of the smallest dimension */
        if (font_size < 10) font_size = 10;
        if (font_size > 30) font_size = 30;

        cairo_select_font_face(cr, "sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_BOLD);
        cairo_set_font_size(cr, font_size);

        /* Measure text for centering */
        cairo_text_extents_t te;
        cairo_text_extents(cr, "WAIT", &te);
        text_x -= te.width / 2.0 + te.x_bearing;
        text_y -= te.y_bearing + (te.height / 3.0);

        /* Draw "WAIT" in bold black */
        cairo_set_source_rgb(cr, 0.0, 0.0, 0.0);
        cairo_move_to(cr, text_x, text_y);
        cairo_show_text(cr, "WAIT");
        cairo_close_path(cr);
    }
}

/* ------------------------------------------------------------------ */
/* Sine wave animation                                                 */
/* ------------------------------------------------------------------ */

/**
 * Timer callback for the sine wave animation.
 * Increments the phase and queues a redraw.
 */
static gboolean animation_tick(gpointer user_data) {
    MainWindow *win = (MainWindow *)user_data;
    win->wave_phase += WAVE_PHASE_INCREMENT;
    gtk_widget_queue_draw(GTK_WIDGET(win->animation_area));
    return TRUE; /* Continue the timer */
}

/**
 * Draw callback for the animation drawing area.
 * Renders the sine wave using Cairo.
 */
static void on_animation_draw(GtkWidget *widget, cairo_t *cr, gpointer user_data) {
    MainWindow *win = (MainWindow *)user_data;

    /* Only draw the sine wave when animation is actively running */
    if (win->animation_source_id == 0) {
        return;
    }

    int width = gtk_widget_get_allocated_width(widget);
    int height = gtk_widget_get_allocated_height(widget);

    if (width <= 0 || height <= 0) {
        return;
    }

    double center_y = height / 2.0;

    /* Set up the sine wave style */
    cairo_set_source_rgba(cr, WAVE_COLOR_R, WAVE_COLOR_G, WAVE_COLOR_B, WAVE_COLOR_A);
    cairo_set_line_width(cr, WAVE_LINE_WIDTH);

    /* Draw the sine wave */
    cairo_move_to(cr, 0, center_y);
    for (int x = 0; x < width; x++) {
        double y = center_y + WAVE_AMPLITUDE *
                   sin(WAVE_FREQUENCY * x + win->wave_phase);
        cairo_line_to(cr, x, y);
    }
    cairo_stroke(cr);
}

/* ------------------------------------------------------------------ */
/* Connection indicator                                                */
/* ------------------------------------------------------------------ */

/**
 * Timer callback for the CHECKING status blink animation.
 * Toggles the blink state and queues a redraw.
 */
static gboolean checking_blink_tick(gpointer user_data) {
    MainWindow *win = (MainWindow *)user_data;
    win->checking_blink = !win->checking_blink;
    gtk_widget_queue_draw(GTK_WIDGET(win->indicator_area));
    return TRUE; /* Continue the timer */
}

/**
 * Start the blink animation for CHECKING status.
 */
static void start_checking_blink(MainWindow *win) {
    if (win->checking_source_id == 0) {
        win->checking_blink = TRUE;
        win->checking_source_id = g_timeout_add(500, checking_blink_tick, win);
    }
}

/**
 * Stop the blink animation for CHECKING status.
 */
static void stop_checking_blink(MainWindow *win) {
    if (win->checking_source_id != 0) {
        g_source_remove(win->checking_source_id);
        win->checking_source_id = 0;
        win->checking_blink = FALSE;
    }
}

/**
 * Draw callback for the connection indicator drawing area.
 * Renders an 8x8 colored circle based on connection status.
 */
static void on_indicator_draw(GtkWidget *widget, cairo_t *cr, gpointer user_data) {
    MainWindow *win = (MainWindow *)user_data;

    int width = gtk_widget_get_allocated_width(widget);
    int height = gtk_widget_get_allocated_height(widget);

    if (width <= 0 || height <= 0) {
        return;
    }

    double cx = width / 2.0;
    double cy = height / 2.0;
    double radius = INDICATOR_SIZE / 2.0;

    ConnectionStatus status = app_get_connection_status(win->controller);

    double r, g, b;
    switch (status) {
        case CONNECTION_LOADING:
            r = COLOR_LOADING_R;
            g = COLOR_LOADING_G;
            b = COLOR_LOADING_B;
            break;
        case CONNECTION_CHECKING:
            r = COLOR_CHECKING_R;
            g = COLOR_CHECKING_G;
            b = COLOR_CHECKING_B;
            /* Blink: only draw when checking_blink is true */
            if (!win->checking_blink) {
                return;
            }
            break;
        case CONNECTION_CONNECTED:
            r = COLOR_CONNECTED_R;
            g = COLOR_CONNECTED_G;
            b = COLOR_CONNECTED_B;
            break;
        case CONNECTION_DISCONNECTED:
        default:
            r = COLOR_DISCONNECTED_R;
            g = COLOR_DISCONNECTED_G;
            b = COLOR_DISCONNECTED_B;
            break;
    }

    cairo_set_source_rgb(cr, r, g, b);
    cairo_arc(cr, cx, cy, radius, 0, 2 * G_PI);
    cairo_fill(cr);
}

/* ------------------------------------------------------------------ */
/* Signal callbacks                                                    */
/* ------------------------------------------------------------------ */

/**
 * Handle button press on the icon area.
 * Toggles the recording state via the state controller.
 */
static gboolean on_icon_button_press(GtkWidget *widget, GdkEventButton *event, gpointer user_data) {
    MainWindow *win = (MainWindow *)user_data;
    (void)widget;
    (void)event;
    if (win->on_toggle) {
        win->on_toggle(win->toggle_user_data);
    }
    return TRUE;
}

/**
 * Handle gear button click.
 * Opens the configuration dialog.
 */
static void on_gear_button_clicked(GtkButton *button, gpointer user_data) {
    (void)button;
    MainWindow *win = (MainWindow *)user_data;
    bool saved = config_dialog_show(win->window, win->config);
    if (saved && win->on_config_changed) {
        win->on_config_changed(win->config_changed_user_data);
    }
}

/**
 * Handle button press on the microphone indicator area.
 * Toggles the recording state: IDLE → LISTENING → TRANSCRIBING → IDLE.
 */
/* CRIT-001 fix: Wrapper to run connection check and update UI */
static gboolean on_indicator_check_connection(gpointer user_data) {
    MainWindow *win = (MainWindow *)user_data;
    if (win && win->whisper_client) {
        bool connected = whisper_check_connection(win->whisper_client);
        ConnectionStatus status = connected ? CONNECTION_CONNECTED : CONNECTION_DISCONNECTED;
        app_window_set_connection_status(win, status);
    }
    return FALSE; /* One-shot */
}

static gboolean on_indicator_button_press(GtkWidget *widget, GdkEventButton *event, gpointer user_data) {
    MainWindow *win = (MainWindow *)user_data;
    (void)widget;
    (void)event;

    /* CRIT-001 fix: Trigger connection check on indicator click */
    app_window_set_connection_status(win, CONNECTION_CHECKING);

    /* Schedule connection check on the main thread */
    g_idle_add(on_indicator_check_connection, win);

    return TRUE;
}

/**
 * Handle window close request.
 * Saves the window position and quits the application.
 * Returns TRUE to prevent GTK from destroying the window —
 * main() handles cleanup after gtk_main() returns.
 */
static gboolean on_window_delete_event(GtkWidget *widget, GdkEvent *event, gpointer user_data) {
    (void)widget;
    (void)event;
    MainWindow *win = (MainWindow *)user_data;
    app_window_save_position(win);
    gtk_main_quit();
    return TRUE; /* Prevent GTK from destroying the window */
}

/**
 * Handle TextWindow close request.
 * Hides the window instead of destroying it.
 */
static gboolean on_text_window_delete_event(GtkWidget *widget, GdkEvent *event, gpointer user_data) {
    gtk_widget_hide(widget);
    (void)user_data;
    (void)event;
    return TRUE; /* Prevent the window from being destroyed */
}

/* MIN-007 fix: Reposition TextWindow when MainWindow moves */
static gboolean on_main_window_configure_event(GtkWidget *widget, GdkEventConfigure *event, gpointer user_data) {
    TextWindow *tw = (TextWindow *)user_data;
    if (!tw || !tw->window || !gtk_widget_get_visible(GTK_WIDGET(tw->window))) {
        return FALSE;
    }
    (void)event;

    int mx, my, mw, mh;
    gtk_window_get_position(GTK_WINDOW(widget), &mx, &my);
    gtk_window_get_size(GTK_WINDOW(widget), &mw, &mh);

    /* Get TextWindow size */
    int tw_w, tw_h;
    gtk_window_get_size(tw->window, &tw_w, &tw_h);

    /* Try to position below MainWindow */
    int tx = mx;
    int ty = my + mh + TEXT_WINDOW_OFFSET_Y;

    /* Check if it would go off the bottom of the screen */
    GdkDisplay *display = gtk_widget_get_display(GTK_WIDGET(tw->window));
    GdkMonitor *mon = gdk_display_get_monitor_at_window(display, gtk_widget_get_window(GTK_WIDGET(tw->window)));
    GdkRectangle monitor;
    gdk_monitor_get_geometry(mon, &monitor);

    if (ty + tw_h > monitor.y + monitor.height) {
        /* Position above the MainWindow instead */
        ty = my - tw_h - TEXT_WINDOW_OFFSET_Y;
        if (ty < monitor.y) {
            ty = monitor.y;
        }
    }

    gtk_window_move(tw->window, tx, ty);

    return FALSE;
}

/* ------------------------------------------------------------------ */
/* Public API — MainWindow Lifecycle                                   */
/* ------------------------------------------------------------------ */

MainWindow *app_window_create(AppConfig *config, AppStateController *controller,
                               WhisperClient *whisper_client) {
    MainWindow *win = (MainWindow *)calloc(1, sizeof(MainWindow));
    if (!win) {
        return NULL;
    }

    win->config = config;
    win->controller = controller;
    win->whisper_client = whisper_client;
    win->animation_source_id = 0;
    win->wave_phase = 0.0;
    win->icon_width = 0;
    win->icon_height = 0;
    win->cached_red_icon = NULL;
    win->cached_green_icon = NULL;
    win->checking_source_id = 0;
    win->checking_blink = FALSE;
    win->countdown_source_id = 0;
    win->countdown_seconds = 0;
    /* Default to TRUE — model has not loaded yet at window creation time.
     * Main() will set to FALSE once the model is fully loaded. */
    win->model_loading = TRUE;

    /* Determine asset directory */
    get_asset_dir(win);

    /* Create the main window */
    win->window = GTK_WINDOW(gtk_window_new(GTK_WINDOW_TOPLEVEL));
    if (!win->window) {
        free(win);
        return NULL;
    }

    /* Set window properties */
    gtk_window_set_title(win->window, "Transcriber");
    gtk_window_set_resizable(win->window, FALSE);
    gtk_window_set_type_hint(win->window, GDK_WINDOW_TYPE_HINT_NORMAL);

    /* Set the window icon (taskbar/dock icon) to the red mic */
    GdkPixbuf *window_icon = load_xpm(win, "redmic.xpm");
    if (window_icon) {
        gtk_window_set_icon(win->window, window_icon);
        g_object_unref(window_icon);
    }

    /* Create the main vertical box */
    win->main_box = GTK_BOX(gtk_box_new(GTK_ORIENTATION_VERTICAL, 0));
    gtk_container_add(GTK_CONTAINER(win->window), GTK_WIDGET(win->main_box));

    /* Create the icon drawing area */
    win->icon_area = GTK_DRAWING_AREA(gtk_drawing_area_new());
    gtk_widget_add_events(GTK_WIDGET(win->icon_area), GDK_BUTTON_PRESS_MASK);
    g_signal_connect(win->icon_area, "draw", G_CALLBACK(on_icon_draw), win);
    g_signal_connect(win->icon_area, "button-press-event",
                     G_CALLBACK(on_icon_button_press), win);

    /* Create the animation drawing area (stacked on top of icon area) */
    win->animation_area = GTK_DRAWING_AREA(gtk_drawing_area_new());
    gtk_widget_add_events(GTK_WIDGET(win->animation_area), GDK_BUTTON_PRESS_MASK);
    g_signal_connect(win->animation_area, "draw", G_CALLBACK(on_animation_draw), win);
    g_signal_connect(win->animation_area, "button-press-event",
                     G_CALLBACK(on_icon_button_press), win);

    /* Use a GtkOverlay to stack icon and animation drawing areas */
    GtkOverlay *overlay = GTK_OVERLAY(gtk_overlay_new());
    gtk_container_add(GTK_CONTAINER(overlay), GTK_WIDGET(win->icon_area));
    gtk_overlay_add_overlay(overlay, GTK_WIDGET(win->animation_area));
    gtk_widget_hide(GTK_WIDGET(win->animation_area));  // Hide until STATE_LISTENING
    gtk_box_pack_start(win->main_box, GTK_WIDGET(overlay), TRUE, TRUE, TRUE);

    /* Create the status bar */
    win->status_bar = GTK_BOX(gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0));
    gtk_widget_set_size_request(GTK_WIDGET(win->status_bar), -1, STATUS_BAR_HEIGHT);
    gtk_box_pack_start(win->main_box, GTK_WIDGET(win->status_bar), FALSE, FALSE, FALSE);

    /* Create the gear button */
    win->gear_button = GTK_BUTTON(gtk_button_new());
    GdkPixbuf *gear_pixbuf = load_xpm(win, "gear.xpm");
    if (gear_pixbuf) {
        /* Scale the gear icon to 16x16 per GNOME HIG for status bar icons */
        int dest_size = 16;
        GdkPixbuf *scaled = gdk_pixbuf_scale_simple(gear_pixbuf, dest_size, dest_size, GDK_INTERP_BILINEAR);
        GtkImage *gear_image = GTK_IMAGE(gtk_image_new_from_pixbuf(scaled));
        gtk_container_add(GTK_CONTAINER(win->gear_button), GTK_WIDGET(gear_image));
        g_object_unref(scaled);
        g_object_unref(gear_pixbuf);
    }
    gtk_widget_set_tooltip_text(GTK_WIDGET(win->gear_button), "Configuration");
    g_signal_connect(win->gear_button, "clicked", G_CALLBACK(on_gear_button_clicked), win);
    gtk_box_pack_start(win->status_bar, GTK_WIDGET(win->gear_button), FALSE, FALSE, 4);

    /* Expander to push countdown to center */
    GtkLabel *spacer_left = GTK_LABEL(gtk_label_new(""));
    gtk_box_pack_start(win->status_bar, GTK_WIDGET(spacer_left), TRUE, TRUE, 0);

    /* Add countdown timer label (centered in status bar) */
    win->countdown_label = GTK_LABEL(gtk_label_new(""));
    gtk_widget_set_no_show_all(GTK_WIDGET(win->countdown_label), FALSE);
    gtk_widget_hide(GTK_WIDGET(win->countdown_label));
    gtk_box_pack_start(win->status_bar, GTK_WIDGET(win->countdown_label), FALSE, FALSE, 0);

    /* Volume level bar (hidden until recording) */
    win->volume_level_bar = GTK_LEVEL_BAR(gtk_level_bar_new());
    gtk_level_bar_set_mode(win->volume_level_bar, GTK_LEVEL_BAR_MODE_CONTINUOUS);
    gtk_level_bar_set_min_value(win->volume_level_bar, 0.0);
    gtk_level_bar_set_max_value(win->volume_level_bar, 1.0);
    gtk_level_bar_set_value(win->volume_level_bar, 0.0);
    /* Add threshold markers: warning at 0.8, critical at 0.95 (clipping) */
    gtk_level_bar_add_offset_value(win->volume_level_bar, "warning", 0.8);
    gtk_level_bar_add_offset_value(win->volume_level_bar, "alert", 0.95);
    gtk_widget_set_size_request(GTK_WIDGET(win->volume_level_bar), 60, 6);
    gtk_widget_hide(GTK_WIDGET(win->volume_level_bar));
    gtk_box_pack_start(win->status_bar, GTK_WIDGET(win->volume_level_bar), FALSE, FALSE, 2);

    /* Expander to push indicator to the right */
    GtkLabel *spacer_right = GTK_LABEL(gtk_label_new(""));
    gtk_box_pack_start(win->status_bar, GTK_WIDGET(spacer_right), TRUE, TRUE, 0);

    /* Create the connection indicator drawing area */
    win->indicator_area = GTK_DRAWING_AREA(gtk_drawing_area_new());
    gtk_widget_set_size_request(GTK_WIDGET(win->indicator_area),
                                INDICATOR_SIZE + 8,
                                INDICATOR_SIZE + 8);
    g_signal_connect(win->indicator_area, "draw", G_CALLBACK(on_indicator_draw), win);
    g_signal_connect(win->indicator_area, "button-press-event",
                     G_CALLBACK(on_indicator_button_press), win);
    gtk_widget_set_tooltip_text(GTK_WIDGET(win->indicator_area),
                                "Connection Status (click to check)");
    gtk_box_pack_start(win->status_bar, GTK_WIDGET(win->indicator_area), FALSE, FALSE, 4);

    /* Connect window delete event */
    g_signal_connect(win->window, "delete-event",
                     G_CALLBACK(on_window_delete_event), win);

    /* Render the initial red mic icon (also resizes window to match icon) */
    render_icon(win, "redmic.xpm");

    /* Position the window from config or defaults */
    int x = config_get_window_x(config);
    int y = config_get_window_y(config);
    if (x < 0) x = DEFAULT_WINDOW_X;
    if (y < 0) y = DEFAULT_WINDOW_Y;
    gtk_window_move(win->window, x, y);

    return win;
}

void app_window_destroy(MainWindow *win) {
    if (!win) return;

    /* Stop animations */
    app_window_stop_animation(win);
    stop_checking_blink(win);

    /* Destroy the GTK window */
    if (win->window) {
        gtk_widget_destroy(GTK_WIDGET(win->window));
    }

    /* Free cached icons (M2-002 fix) */
    if (win->cached_red_icon) {
        g_object_unref(win->cached_red_icon);
    }
    if (win->cached_green_icon) {
        g_object_unref(win->cached_green_icon);
    }

    /* Free the structure */
    free(win);
}

GtkWindow *app_window_get_gtk_window(MainWindow *win) {
    if (!win) return NULL;
    return win->window;
}

/* ------------------------------------------------------------------ */
/* Public API — MainWindow State Updates                               */
/* ------------------------------------------------------------------ */

void app_window_set_state(MainWindow *win, AppState state) {
    if (!win) return;

    switch (state) {
        case STATE_IDLE:
            render_icon(win, "redmic.xpm");
            /* Update taskbar icon to red mic (cached, M2-002 fix) */
            { GdkPixbuf *icon = get_cached_icon(win, "redmic.xpm");
              if (icon) { gtk_window_set_icon(win->window, icon); g_object_unref(icon); } }
            app_window_stop_animation(win);
            gtk_widget_hide(GTK_WIDGET(win->volume_level_bar));
            gtk_level_bar_set_value(win->volume_level_bar, 0.0);
            break;
        case STATE_LISTENING:
            render_icon(win, "greenmic.xpm");
            /* Update taskbar icon to green mic (cached, M2-002 fix) */
            { GdkPixbuf *icon = get_cached_icon(win, "greenmic.xpm");
              if (icon) { gtk_window_set_icon(win->window, icon); g_object_unref(icon); } }
            gtk_widget_show(GTK_WIDGET(win->animation_area));
            gtk_widget_show(GTK_WIDGET(win->volume_level_bar));
            app_window_start_animation(win);
            app_window_start_countdown(win);
            break;
        case STATE_TRANSCRIBING:
            render_icon(win, "greenmic.xpm");
            /* Update taskbar icon to green mic (cached, M2-002 fix) */
            { GdkPixbuf *icon = get_cached_icon(win, "greenmic.xpm");
              if (icon) { gtk_window_set_icon(win->window, icon); g_object_unref(icon); } }
            app_window_stop_animation(win);
            gtk_widget_hide(GTK_WIDGET(win->animation_area));
            gtk_widget_hide(GTK_WIDGET(win->volume_level_bar));
            app_window_stop_countdown(win);
            break;
    }
}

void app_window_set_connection_status(MainWindow *win, ConnectionStatus status) {
    if (!win) return;

    /* Stop any existing blink animation */
    stop_checking_blink(win);

    /* Start blink animation for CHECKING status */
    if (status == CONNECTION_CHECKING) {
        start_checking_blink(win);
    }

    /* Queue a redraw on the indicator */
    gtk_widget_queue_draw(GTK_WIDGET(win->indicator_area));
}

void app_window_start_animation(MainWindow *win) {
    if (!win) return;

    /* Don't start if already running */
    if (win->animation_source_id != 0) {
        return;
    }

    win->wave_phase = 0.0;
    win->animation_source_id = g_timeout_add(ANIMATION_INTERVAL_MS,
                                              animation_tick,
                                              win);
}

void app_window_stop_animation(MainWindow *win) {
    if (!win) return;

    if (win->animation_source_id != 0) {
        g_source_remove(win->animation_source_id);
        win->animation_source_id = 0;
    }

    /* Clear the animation area */
    gtk_widget_queue_draw(GTK_WIDGET(win->animation_area));
    gtk_widget_hide(GTK_WIDGET(win->animation_area));
}

/* ------------------------------------------------------------------ */
/* Countdown Timer                                                     */
/* ------------------------------------------------------------------ */

static gboolean countdown_tick(gpointer user_data) {
    MainWindow *win = (MainWindow *)user_data;
    win->countdown_seconds--;
    if (win->countdown_seconds <= 0) {
        win->countdown_seconds = 0;
        gtk_label_set_text(win->countdown_label, "0");
        g_source_remove(win->countdown_source_id);
        win->countdown_source_id = 0;
        return FALSE;
    }
    gchar buf[8];
    g_snprintf(buf, sizeof(buf), "%d", win->countdown_seconds);
    gtk_label_set_text(win->countdown_label, buf);
    return TRUE; /* Continue the timer */
}

void app_window_start_countdown(MainWindow *win) {
    if (!win) return;

    /* Stop any existing countdown */
    if (win->countdown_source_id != 0) {
        g_source_remove(win->countdown_source_id);
        win->countdown_source_id = 0;
    }

    /* Get max_duration from config */
    int max_duration = 30; /* default */
    if (win->config) {
        max_duration = win->config->max_duration;
        if (max_duration <= 0) max_duration = 30;
    }

    win->countdown_seconds = max_duration;
    gchar buf[8];
    g_snprintf(buf, sizeof(buf), "%d", win->countdown_seconds);
    gtk_label_set_text(win->countdown_label, buf);
    gtk_widget_show(GTK_WIDGET(win->countdown_label));

    win->countdown_source_id = g_timeout_add_seconds(1, countdown_tick, win);
}

void app_window_stop_countdown(MainWindow *win) {
    if (!win) return;

    if (win->countdown_source_id != 0) {
        g_source_remove(win->countdown_source_id);
        win->countdown_source_id = 0;
    }

    gtk_label_set_text(win->countdown_label, "");
    gtk_widget_hide(GTK_WIDGET(win->countdown_label));
}

void app_window_save_position(MainWindow *win) {
    if (!win || !win->window || !win->config) return;

    int x, y;
    gtk_window_get_position(win->window, &x, &y);
    config_set_window_position(win->config, x, y);
    config_save(win->config);  /* Persist to disk */
}

void app_window_set_toggle_callback(MainWindow *win,
                                    void (*callback)(void *user_data),
                                    void *user_data) {
    if (!win) return;
    win->on_toggle = callback;
    win->toggle_user_data = user_data;
}

void app_window_set_config_changed_callback(MainWindow *win,
                                            void (*callback)(void *user_data),
                                            void *user_data) {
    if (!win) return;
    win->on_config_changed = callback;
    win->config_changed_user_data = user_data;
}

/* ------------------------------------------------------------------ */
/* Public API — TextWindow Lifecycle                                   */
/* ------------------------------------------------------------------ */

TextWindow *app_text_window_create(GtkWindow *main_window_gtk) {
    TextWindow *tw = (TextWindow *)calloc(1, sizeof(TextWindow));
    if (!tw) {
        return NULL;
    }

    /* Create the text window */
    tw->window = GTK_WINDOW(gtk_window_new(GTK_WINDOW_TOPLEVEL));
    if (!tw->window) {
        free(tw);
        return NULL;
    }

    /* Set window properties */
    gtk_window_set_title(tw->window, "Transcription");
    gtk_window_set_resizable(tw->window, TRUE);
    gtk_window_set_type_hint(tw->window, GDK_WINDOW_TYPE_HINT_UTILITY);
    /* Note: Not setting transient_for or destroy_with_parent because the main
     * window is hidden (tray app). Setting these causes the window manager to
     * send a delete-event to the TextWindow immediately after showing it. */

    /* Position below MainWindow, with screen boundary check */
    if (main_window_gtk && gtk_widget_get_visible(GTK_WIDGET(main_window_gtk))) {
        int mx, my, mw, mh;
        gtk_window_get_position(main_window_gtk, &mx, &my);
        gtk_window_get_size(main_window_gtk, &mw, &mh);

        /* Get TextWindow size */
        int tw_w, tw_h;
        gtk_window_get_size(tw->window, &tw_w, &tw_h);

        /* Try to position below MainWindow */
        int tx = mx;
        int ty = my + mh + TEXT_WINDOW_OFFSET_Y;

        /* Check if it would go off the bottom of the screen */
        GdkDisplay *display = gtk_widget_get_display(GTK_WIDGET(tw->window));
        GdkMonitor *mon = gdk_display_get_monitor_at_window(display, gtk_widget_get_window(GTK_WIDGET(tw->window)));
        GdkRectangle monitor;
        gdk_monitor_get_geometry(mon, &monitor);

        if (ty + tw_h > monitor.y + monitor.height) {
            /* Position above the MainWindow instead */
            ty = my - tw_h - TEXT_WINDOW_OFFSET_Y;
            if (ty < monitor.y) {
                ty = monitor.y;
            }
        }

        gtk_window_move(tw->window, tx, ty);
    }

    /* Set default size */
    gtk_window_set_default_size(tw->window, 400, 200);

    /* Create the text view */
    tw->text_view = GTK_TEXT_VIEW(gtk_text_view_new());
    gtk_text_view_set_wrap_mode(tw->text_view, GTK_WRAP_WORD_CHAR);
    gtk_text_view_set_editable(tw->text_view, TRUE);
    gtk_text_view_set_cursor_visible(tw->text_view, TRUE);
    /* Undo requires GtkSourceView (not available) */

    /* Get the text buffer */
    tw->buffer = gtk_text_view_get_buffer(tw->text_view);

    /* Add text view to a scrolled window */
    GtkScrolledWindow *scrolled = GTK_SCROLLED_WINDOW(gtk_scrolled_window_new(NULL, NULL));
    gtk_scrolled_window_set_policy(scrolled, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
    gtk_container_add(GTK_CONTAINER(scrolled), GTK_WIDGET(tw->text_view));

    /* Add scrolled window to the text window */
    gtk_container_add(GTK_CONTAINER(tw->window), GTK_WIDGET(scrolled));

    /* Connect delete event to hide (not destroy) */
    g_signal_connect(tw->window, "delete-event",
                      G_CALLBACK(on_text_window_delete_event), tw);

    /* MIN-007 fix: Listen for MainWindow position changes */
    if (main_window_gtk) {
        g_signal_connect(main_window_gtk, "configure-event",
                         G_CALLBACK(on_main_window_configure_event), tw);
    }

    return tw;
}

void app_text_window_destroy(TextWindow *tw) {
    if (!tw) return;

    if (tw->window) {
        gtk_widget_destroy(GTK_WIDGET(tw->window));
    }

    free(tw);
}

void app_text_window_append_text(TextWindow *tw, const char *text) {
    if (!tw || !text) return;

    /* Append text to the buffer */
    GtkTextIter end;
    gtk_text_buffer_get_end_iter(tw->buffer, &end);
    gtk_text_buffer_insert(tw->buffer, &end, text, -1);
    gtk_text_buffer_insert(tw->buffer, &end, "\n", 1);

    /* Show and raise the window */
    gtk_widget_show_all(GTK_WIDGET(tw->window));
    gtk_window_present(tw->window);

    /* Scroll to the end */
    gtk_text_buffer_get_end_iter(tw->buffer, &end);
    gtk_text_view_scroll_to_iter(tw->text_view, &end, 0, FALSE, 0, 0);
}

void app_text_window_set_error(TextWindow *tw, const char *error) {
    if (!tw || !error) return;

    /* Prefix with "ERROR: " */
    GtkTextIter end;
    gtk_text_buffer_get_end_iter(tw->buffer, &end);
    gtk_text_buffer_insert(tw->buffer, &end, "ERROR: ", 7);
    gtk_text_buffer_insert(tw->buffer, &end, error, -1);
    gtk_text_buffer_insert(tw->buffer, &end, "\n", 1);

    /* Show and raise the window */
    gtk_widget_show_all(GTK_WIDGET(tw->window));
    gtk_window_present(tw->window);
}

/* MIN-001 fix: Removed unused app_text_window_get_text() and app_text_window_is_visible(). */

void app_window_set_volume_level(MainWindow *win, double level) {
    if (!win || !win->volume_level_bar) return;
    if (level < 0.0) level = 0.0;
    if (level > 1.0) level = 1.0;
    gtk_level_bar_set_value(win->volume_level_bar, level);
}

void app_window_set_model_loading(MainWindow *win, bool model_loading) {
    if (!win) return;
    if (win->model_loading == model_loading) return;  /* No change */
    win->model_loading = model_loading;
    /* Queue a redraw to show/remove the "WAIT" overlay */
    gtk_widget_queue_draw(GTK_WIDGET(win->icon_area));
}

bool app_window_get_model_loading(MainWindow *win) {
    if (!win) return FALSE;
    return win->model_loading;
}
