/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Piyush Raizada <piyush.raizada@gmail.com>
 *
 * This file is part of the Transcriber project.
 * See the LICENSE file for full license text.
 */

/**
 * @file app_tray.c
 * @brief System Tray Icon — libappindicator integration for notification area presence
 *
 * This module implements the system tray (notification area) icon for the
 * Transcriber application. It uses libappindicator (Ayatana fork preferred,
 * with fallback to original libappindicator) to create a StatusNotifierItem
 * that appears in the desktop environment's system tray / notification area.
 *
 * Features:
 *   - State-aware icon (red mic for IDLE, green mic for LISTENING/TRANSCRIBING)
 *   - Dynamic tooltip reflecting current state and connection status
 *   - Right-click context menu with Toggle Recording, Show Window, Quit
 *
 * Icon Handling:
 *   The embedded XPM arrays (from CMake) are converted to GdkPixbuf, then saved
 *   as temporary PNG files in the system temp directory for AppIndicator
 *   consumption. These temp files are cleaned up in tray_destroy().
 *
 * Context Menu:
 *   Built with GtkMenu (GTK3). Items are:
 *     - "Toggle Recording" — calls the registered toggle callback
 *     - "Show Window"      — presents the main GtkWindow
 *     - "Quit"             — calls gtk_main_quit()
 *
 * @see app_tray.h for public API documentation
 * @see plans/system-tray-icon.md for full design documentation
 */

#define _POSIX_C_SOURCE 200809L

#include "app_tray.h"
#include "app.h"

#include <glib.h>
#include <libayatana-appindicator/app-indicator.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <libgen.h>
#include <limits.h>
#include <sys/stat.h>

/* Embedded XPM assets (generated by CMake) */
#ifdef XPM_STATICALLY_EMBEDDED
#include "assets/greenmic.h"
#include "assets/redmic.h"
#endif

/* ------------------------------------------------------------------ */
/* Internal constants                                                  */
/* ------------------------------------------------------------------ */

/** Reverse-DNS style indicator ID for uniqueness. */
#define TRAY_ID "com.example.transcriber"

/** Tooltip strings per state. */
#define TOOLTIP_IDLE_CONNECTED    "Transcriber — Ready"
#define TOOLTIP_IDLE_DISCONNECTED "Transcriber — Model unavailable"
#define TOOLTIP_LISTENING         "Transcriber — Recording..."
#define TOOLTIP_TRANSCRIBING      "Transcriber — Transcribing..."
#define TOOLTIP_LOADING           "Transcriber — Loading model..."

/** Temp file base names (combined with g_get_tmp_dir() at runtime). */
#define TRAY_ICON_IDLE_NAME     "transcriber_tray_idle"
#define TRAY_ICON_LISTENING_NAME "transcriber_tray_listening"

/* ------------------------------------------------------------------ */
/* Internal structures                                                 */
/* ------------------------------------------------------------------ */

struct _SystemTray {
    AppIndicator *indicator;      /* The AppIndicator handle */
    GtkMenu *menu;                /* Right-click context menu */
    GtkWindow *main_window;       /* Reference to main window for "Show" */
    AppState current_state;       /* Current application state */
    ConnectionStatus conn_status; /* Current connection status */
    /* Toggle callback — invoked when "Toggle Recording" is selected */
    void (*on_toggle)(void *user_data);
    void *toggle_user_data;
    /* Dynamic temp icon directory and file paths */
    char icon_dir[PATH_MAX];
    char icon_idle_path[PATH_MAX];
    char icon_listening_path[PATH_MAX];
    /* Icon names for app_indicator_set_icon() (basename without extension) */
    char icon_idle_name[64];
    char icon_listening_name[64];
    /* Track which temp icon files were created for cleanup */
    bool icon_idle_created;
    bool icon_listening_created;
};

/* ------------------------------------------------------------------ */
/* Static helper function declarations                                 */
/* ------------------------------------------------------------------ */

static GdkPixbuf *load_xpm_for_tray(const char *filename);
static gboolean save_pixbuf_as_png(GdkPixbuf *pixbuf, const char *path);
static void ensure_icon_files(SystemTray *tray);
static void update_tray_icon(SystemTray *tray);
static void update_tray_tooltip(SystemTray *tray);
static void build_context_menu(SystemTray *tray);

/* Menu item callbacks */
static void on_menu_toggle(GtkMenuItem *item, gpointer user_data);
static void on_menu_show(GtkMenuItem *item, gpointer user_data);
static void on_menu_quit(GtkMenuItem *item, gpointer user_data);

/* ------------------------------------------------------------------ */
/* Icon loading and PNG conversion                                     */
/* ------------------------------------------------------------------ */

/**
 * Load an XPM icon into a GdkPixbuf using the embedded arrays.
 * Falls back to loading from the assets/ directory on disk.
 */
static GdkPixbuf *load_xpm_for_tray(const char *filename) {
    GdkPixbuf *pixbuf = NULL;

#ifdef XPM_STATICALLY_EMBEDDED
    if (strcmp(filename, "greenmic.xpm") == 0) {
        pixbuf = gdk_pixbuf_new_from_xpm_data(GREENMIC_XPM);
    } else if (strcmp(filename, "redmic.xpm") == 0) {
        pixbuf = gdk_pixbuf_new_from_xpm_data(REDMIC_XPM);
    }
#else
    /* Fallback: load from disk */
    char path[PATH_MAX];
    /* Try relative to executable */
    char exe_path[PATH_MAX];
    ssize_t len = readlink("/proc/self/exe", exe_path, sizeof(exe_path) - 1);
    if (len != -1) {
        exe_path[len] = '\0';
        char *dir = dirname(exe_path);
        snprintf(path, sizeof(path), "%s/assets/%s", dir, filename);
        pixbuf = gdk_pixbuf_new_from_file(path, NULL);
    }
    /* Try relative to current directory */
    if (!pixbuf) {
        snprintf(path, sizeof(path), "./assets/%s", filename);
        pixbuf = gdk_pixbuf_new_from_file(path, NULL);
    }
#endif

    return pixbuf;
}

/**
 * Save a GdkPixbuf as a PNG file to the given path.
 *
 * @return TRUE on success, FALSE on failure (with error logged to stderr).
 */
static gboolean save_pixbuf_as_png(GdkPixbuf *pixbuf, const char *path) {
    GError *error = NULL;
    gboolean ok = gdk_pixbuf_save(pixbuf, path, "png", &error, NULL);
    if (!ok) {
        /* CR-02 fix: 'error' may be NULL if gdk_pixbuf_save fails without setting GError */
        g_warning("[tray] Failed to save icon to %s: %s",
                  path, error ? error->message : "unknown error");
        g_error_free(error);
    }
    return ok;
}

/**
 * Ensure the temporary PNG icon files exist on disk.
 * Converts embedded XPM -> GdkPixbuf -> PNG for AppIndicator use.
 * Icons are saved in the tray->icon_dir directory with names like
 * "transcriber_tray_idle.png" so app_indicator_set_icon() can find them
 * via the icon theme path set by app_indicator_new_with_path().
 */
static void ensure_icon_files(SystemTray *tray) {
    /* Create IDLE icon (red mic) */
    if (!tray->icon_idle_created) {
        GdkPixbuf *pixbuf = load_xpm_for_tray("redmic.xpm");
        if (pixbuf && save_pixbuf_as_png(pixbuf, tray->icon_idle_path)) {
            tray->icon_idle_created = true;
        }
        if (pixbuf) {
            g_object_unref(pixbuf);
        }
    }

    /* Create LISTENING/TRANSCRIBING icon (green mic) */
    if (!tray->icon_listening_created) {
        GdkPixbuf *pixbuf = load_xpm_for_tray("greenmic.xpm");
        if (pixbuf && save_pixbuf_as_png(pixbuf, tray->icon_listening_path)) {
            tray->icon_listening_created = true;
        }
        if (pixbuf) {
            g_object_unref(pixbuf);
        }
    }
}

/* ------------------------------------------------------------------ */
/* Context menu                                                        */
/* ------------------------------------------------------------------ */

/**
 * Build the right-click context menu for the tray icon.
 */
static void build_context_menu(SystemTray *tray) {
    tray->menu = GTK_MENU(gtk_menu_new());

    /* "Toggle Recording" menu item */
    GtkWidget *toggle_item = gtk_menu_item_new_with_label("Toggle Recording");
    g_signal_connect_swapped(toggle_item, "activate",
                             G_CALLBACK(on_menu_toggle), tray);
    gtk_menu_shell_append(GTK_MENU_SHELL(tray->menu), toggle_item);

    /* "Show Window" menu item */
    GtkWidget *show_item = gtk_menu_item_new_with_label("Show Window");
    g_signal_connect_swapped(show_item, "activate",
                             G_CALLBACK(on_menu_show), tray);
    gtk_menu_shell_append(GTK_MENU_SHELL(tray->menu), show_item);

    /* Separator */
    GtkWidget *separator = gtk_separator_menu_item_new();
    gtk_menu_shell_append(GTK_MENU_SHELL(tray->menu), separator);

    /* "Quit" menu item */
    GtkWidget *quit_item = gtk_menu_item_new_with_label("Quit");
    g_signal_connect_swapped(quit_item, "activate",
                             G_CALLBACK(on_menu_quit), tray);
    gtk_menu_shell_append(GTK_MENU_SHELL(tray->menu), quit_item);

    /* Show all menu items */
    gtk_widget_show_all(GTK_WIDGET(tray->menu));

    /* Attach menu to the indicator */
    app_indicator_set_menu(tray->indicator, GTK_MENU(tray->menu));
}

/* ------------------------------------------------------------------ */
/* Menu item callback implementations                                  */
/* ------------------------------------------------------------------ */

static void on_menu_toggle(GtkMenuItem *item, gpointer user_data) {
    (void)item;
    SystemTray *tray = (SystemTray *)user_data;
    if (tray->on_toggle) {
        tray->on_toggle(tray->toggle_user_data);
    }
}

static void on_menu_show(GtkMenuItem *item, gpointer user_data) {
    (void)item;
    SystemTray *tray = (SystemTray *)user_data;
    if (tray->main_window) {
        gtk_window_present(tray->main_window);
    }
}

static void on_menu_quit(GtkMenuItem *item, gpointer user_data) {
    (void)item;
    (void)user_data;
    gtk_main_quit();
}

/* ------------------------------------------------------------------ */
/* Icon and tooltip updates                                            */
/* ------------------------------------------------------------------ */

/**
 * Update the tray icon based on current state.
 * Uses icon names (not full paths) with the custom icon theme path
 * set by app_indicator_new_with_path().
 */
static void update_tray_icon(SystemTray *tray) {
    ensure_icon_files(tray);

    const char *icon_name = NULL;
    switch (tray->current_state) {
        case STATE_LISTENING:
        case STATE_TRANSCRIBING:
            if (tray->icon_listening_created) {
                icon_name = tray->icon_listening_name;
            }
            break;
        case STATE_IDLE:
        default:
            if (tray->icon_idle_created) {
                icon_name = tray->icon_idle_name;
            }
            break;
    }

    if (icon_name) {
        app_indicator_set_icon(tray->indicator, icon_name);
    }
}

/**
 * Update the tray tooltip and label based on current state and connection status.
 */
static void update_tray_tooltip(SystemTray *tray) {
    const char *tooltip;

    switch (tray->current_state) {
        case STATE_LISTENING:
            tooltip = TOOLTIP_LISTENING;
            break;
        case STATE_TRANSCRIBING:
            tooltip = TOOLTIP_TRANSCRIBING;
            break;
        case STATE_IDLE:
        default:
            if (tray->conn_status == CONNECTION_LOADING) {
                tooltip = TOOLTIP_LOADING;
            } else if (tray->conn_status == CONNECTION_CONNECTED) {
                tooltip = TOOLTIP_IDLE_CONNECTED;
            } else {
                tooltip = TOOLTIP_IDLE_DISCONNECTED;
            }
            break;
    }

    /* Set the label (tooltip) on the indicator.
     * The third argument (secondary_label) is NULL — we only need the main label. */
    app_indicator_set_label(tray->indicator, tooltip, NULL);

    /* Ensure the indicator is visible in the system tray */
    app_indicator_set_status(tray->indicator, APP_INDICATOR_STATUS_ACTIVE);
}

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

SystemTray *tray_create(void) {
    SystemTray *tray = calloc(1, sizeof(SystemTray));
    if (!tray) {
        return NULL;
    }

    tray->current_state = STATE_IDLE;
    tray->conn_status = CONNECTION_DISCONNECTED;
    tray->main_window = NULL;
    tray->on_toggle = NULL;
    tray->toggle_user_data = NULL;
    tray->icon_idle_created = false;
    tray->icon_listening_created = false;

    /* Create a temp directory for icon files so app_indicator_new_with_path()
     * can find them. This is required because app_indicator_set_icon() expects
     * an icon name (not a full path) and searches the icon theme path. */
    g_snprintf(tray->icon_dir, sizeof(tray->icon_dir),
               "%s/transcriber_icons_%d", g_get_tmp_dir(), getpid());
    mkdir(tray->icon_dir, 0755);

    /* Build icon file paths within the temp directory */
    g_snprintf(tray->icon_idle_path, sizeof(tray->icon_idle_path),
               "%s/%s.png", tray->icon_dir, TRAY_ICON_IDLE_NAME);
    g_snprintf(tray->icon_listening_path, sizeof(tray->icon_listening_path),
               "%s/%s.png", tray->icon_dir, TRAY_ICON_LISTENING_NAME);

    /* Icon names (basename without extension) for app_indicator_set_icon() */
    snprintf(tray->icon_idle_name, sizeof(tray->icon_idle_name), "%s", TRAY_ICON_IDLE_NAME);
    snprintf(tray->icon_listening_name, sizeof(tray->icon_listening_name), "%s", TRAY_ICON_LISTENING_NAME);

    /* Create the icon PNG files BEFORE app_indicator_new_with_path().
     * The AppIndicator constructor attempts to load the initial icon
     * immediately. If the file doesn't exist, internal GTK widgets end up
     * in an invalid (NULL) state, causing a cascade of G_IS_OBJECT and
     * GTK_IS_CELL_RENDERER assertion failures followed by a segfault. */
    ensure_icon_files(tray);

    /* Create the AppIndicator with custom icon theme path */
    tray->indicator = app_indicator_new_with_path(TRAY_ID, tray->icon_idle_name,
                                           APP_INDICATOR_CATEGORY_APPLICATION_STATUS,
                                           tray->icon_dir);
    if (!tray->indicator) {
        g_log("app-tray", G_LOG_LEVEL_MESSAGE, "[tray] Failed to create AppIndicator\n");
        rmdir(tray->icon_dir);
        free(tray);
        return NULL;
    }

    /* Build the context menu */
    build_context_menu(tray);

    /* Set initial icon and status */
    update_tray_icon(tray);
    update_tray_tooltip(tray);

    return tray;
}

void tray_destroy(SystemTray *tray) {
    if (!tray) return;

    /* Remove temporary icon files */
    if (tray->icon_idle_created) {
        unlink(tray->icon_idle_path);
    }
    if (tray->icon_listening_created) {
        unlink(tray->icon_listening_path);
    }

    /* Remove temporary icon directory */
    rmdir(tray->icon_dir);

    /* Free GTK resources */
    if (tray->menu) {
        gtk_widget_destroy(GTK_WIDGET(tray->menu));
    }

    /* Free the indicator (this is a GObject) */
    if (tray->indicator) {
        g_object_unref(tray->indicator);
    }

    free(tray);
}

void tray_set_state(SystemTray *tray, AppState state) {
    if (!tray) return;

    tray->current_state = state;
    update_tray_icon(tray);
    update_tray_tooltip(tray);
}

void tray_set_connection_status(SystemTray *tray, ConnectionStatus status) {
    if (!tray) return;

    tray->conn_status = status;
    /* Only update tooltip if in IDLE state (connection matters most then) */
    if (tray->current_state == STATE_IDLE) {
        update_tray_tooltip(tray);
    }
}

void tray_set_main_window(SystemTray *tray, GtkWindow *win) {
    if (!tray) return;
    tray->main_window = win;
}

void tray_set_toggle_callback(SystemTray *tray,
                              void (*callback)(void *user_data),
                              void *user_data) {
    if (!tray) return;
    tray->on_toggle = callback;
    tray->toggle_user_data = user_data;
}
